[package]
name = "tui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

crossterm = "0.27.0"
tree-sitter = "0.20.10"
tree-sitter-rust = "0.20.4"
tree-sitter-highlight = "^0.20.1"

